### ISSUE TITLE
All Discord invitation links have expired

### ISSUE THREAD

**Issue by TakWolf** [Telltale-Modding-Group/.github#1]
Does the community still exist? How to enter？

@frostbone25

**Comment by TakWolf** [comment]
I want to find some information for '.font' format in Telltale engine.

Specifically, I hope to be able to replace the custom font of the game.

But I can't find the relevant information, and I'm not sure if anyone can help me.

Thanks!

**Comment by frostbone25** [comment]
> Does the community still exist? How to enter？
> 
> 
> 
> @frostbone25 

Sorry about that, the link should be updated now.
